# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_ref',
            new_name='link_url',
        ),
        migrations.AddField(
            model_name='bucket',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
